In [4]:
import numpy as np

In [6]:
a=[]
n=int(input("Enter the size of the array:"))
for i in range (n):
    val=int(input("Enter the number one by one:"))
    a.append(val)
    myarray=np.array(a)
    myarray


Enter the size of the array:1
Enter the number one by one:2


In [7]:
a=[[1,2,3],[3,4,5],[6,7,8]]
arr=np.array(a)
print("Dimension of the array is=",arr.ndim)

Dimension of the array is= 2


In [8]:
a=[[1,2,3],[3,4,5],[6,7,8]]
arr=np.array(a)
print("Shape of the array is=",arr.shape)

Shape of the array is= (3, 3)


In [21]:
import numpy as np
arr=np.random.rand(2,3)

arr

array([[0.91688837, 0.48500369, 0.53986661],
       [0.59106253, 0.90184291, 0.12278085]])

In [25]:
import numpy as np
a=[]
n=int(input("Enter the size of the array?"))
for i in range(n):
    val=int(input("Enter the number one by one:"))
    a.append(val)
arr=np.array(a)
for i in range(arr.size):
    print(arr[i])
    sum=0
for i in range(arr.size):
    sum=sum+arr[i]
print("sum of array elements=",sum)
arr1=arr[-4:]
print(arr1)
    
           

Enter the size of the array?5
Enter the number one by one:1
Enter the number one by one:2
Enter the number one by one:3
Enter the number one by one:4
Enter the number one by one:5
1
2
3
4
5
sum of array elements= 15
[2 3 4 5]


In [32]:
import numpy as np
arr=np.random.randint(1,100,12)
arr=arr.reshape(6,2)
print(arr)
print("No of Dimension=",arr.shape)

[[55 91]
 [88 89]
 [12 95]
 [94 54]
 [85 88]
 [19 41]]
No of Dimension= (6, 2)


In [41]:
import numpy as np
np.random.seed(12)
arr=np.random.randint(1,100,12)
arr.size

12

In [50]:
import numpy as np
matrix=[]
row=int(input("Enter the no of rows:"))
col=int(input("Enter the no of columns:"))
for i in range(row):
  a=[]
  for j in range(col):
        val=int(input("Enter the numbers one by one:"))
        a.append(val)
  matrix.append(a)
arr=np.array(matrix)
for i in range (row):
    for j in range (col):
        print(arr[i,j],end="")
    print()
print(type(arr))

Enter the no of rows:3
Enter the no of columns:3
Enter the numbers one by one:1
Enter the numbers one by one:2
Enter the numbers one by one:3
Enter the numbers one by one:4
Enter the numbers one by one:5
Enter the numbers one by one:6
Enter the numbers one by one:7
Enter the numbers one by one:8
Enter the numbers one by one:9
123
456
789
<class 'numpy.ndarray'>


In [12]:
import numpy as np
np.random.seed(121)
arr=np.random.randint(1,10000,100).reshape(10,10)
arr
arr[0:,2:]

array([[9824, 2114, 5813, 8532, 3584, 2815,  949, 6199],
       [7226, 1100, 9945, 8679, 4392, 4886, 2346, 9016],
       [9524, 4107, 7556, 3397, 7763, 7951, 7256, 5087],
       [6687, 2309, 4014, 4733,  205,  529, 5000, 8768],
       [1315,  382, 2050,  229, 5576,   14, 9231, 6657],
       [4002, 5002, 7685, 7380, 6563, 9800, 4235, 6206],
       [3757, 8811, 2535,  131, 8771, 2564, 2019, 3636],
       [1932, 1175, 2129, 1810, 9167, 5495,  833, 2852],
       [6183, 3640, 1461, 9513, 2415, 6536, 8980, 3969],
       [6780, 4757, 7037,  484, 6051, 8172, 2580, 7884]])

In [16]:
import numpy as np
a=np.array([56,89,45,34,27,78,98,2312,89,49])
b=a[2:7].copy()
b[:]=0
a

array([  56,   89,   45,   34,   27,   78,   98, 2312,   89,   49])

In [25]:
import numpy as np
a=np.arange(1,20)
a[a%10==0]=0
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9,  0, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [31]:
import numpy as np
arr1=np.arange(1,10)
arr2=np.arange(11,20)


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
arr1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
arr2

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

In [34]:
arr1+arr2

array([12, 14, 16, 18, 20, 22, 24, 26, 28])

In [35]:
arr1*arr2

array([ 11,  24,  39,  56,  75,  96, 119, 144, 171])

In [ ]:
import numpy as np
a=np.array([1,2,3,4]).reshape(2,2)
b=np.array([5,6,7,8]).reshape(2,2)

In [44]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9,  0, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [45]:
b

array([0, 0, 0, 0, 0])

In [ ]:
import numpy as np


In [ ]:
a=np.array([1,2,3,4]).reshape(2,2)
b=np.array([5,6,7,8]).reshape(2,2)

In [47]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9,  0, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [56]:
import numpy as np
arr=np.array([10,20,30,40,50,60])
np.cos(arr)

array([-0.83907153,  0.40808206,  0.15425145, -0.66693806,  0.96496603,
       -0.95241298])

In [61]:
import numpy as np
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [65]:
import numpy as np
np.random.seed(122)
matrix=np.random.randint(1,21,9).reshape(3,3)
matrix

array([[16, 11, 13],
       [17, 13, 16],
       [ 3, 16, 11]])

In [75]:
np.cumsum(matrix)

array([ 16,  27,  40,  57,  70,  86,  89, 105, 116])

In [80]:
import numpy as np
np.random.seed(122)
matrix=np.random.randint(1,21,9)
np.random.shuffle(matrix)
matrix

array([13, 16,  3, 11, 13, 17, 11, 16, 16])

In [87]:
import numpy as np
arr=np.array([10,20,30,40,50,60,10,30,50,20,70,80])
np.unique(arr,return_index=True,return_counts=True)


(array([10, 20, 30, 40, 50, 60, 70, 80]),
 array([ 0,  1,  2,  3,  4,  5, 10, 11]),
 array([2, 2, 2, 1, 2, 1, 1, 1]))

In [91]:
import numpy as np
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [98]:
import numpy as np
np.random.seed(122)
arr1=np.random.randint(1,21,9).reshape(3,3)
arr2=np.random.randint(50,71,9).reshape(3,3)
np.vstack((arr1,arr2))

array([[16, 11, 13],
       [17, 13, 16],
       [ 3, 16, 11],
       [59, 56, 64],
       [53, 54, 69],
       [69, 63, 50]])

In [96]:
arr1

array([[16, 11, 13],
       [17, 13, 16],
       [ 3, 16, 11]])

In [97]:
arr2

array([[59, 56, 64],
       [53, 54, 69],
       [69, 63, 50]])

In [102]:
import numpy as np
arr=np.full((1,1,100),7)
arr

array([[[7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7,
         7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7,
         7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7,
         7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7,
         7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7]]])

In [104]:
%%timeit
a=[]
for i in range(1,16):
    a.append(i*10)

1.01 µs ± 4.67 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [106]:
%timeit [i**2 for i in range (1,11)]

2.57 µs ± 15.7 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [108]:
import numpy as np
%timeit np.arange(1,11)**2

986 ns ± 10.1 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [110]:
import numpy as np
arr=np.array([17,29,44,74,12,67,34,56,78,989])
pos=np.searchsorted(a,56,side='right')
print(pos)


4


In [113]:
import numpy as np
arr=np.array([1,3,5,7,11,15,23,46,78,236,906])
result=np.where(arr%2==0)
print(result)

(array([ 7,  8,  9, 10]),)


In [1]:
import tensorflow as tf


ModuleNotFoundError: No module named 'tensorflow'

In [2]:
import numpy as np